/**
 * EntityOS seed — spreadsheet-driven.
 *
 * Data source: prisma/data/seed-data.json, generated by prisma/data/parse_xlsx.py
 * from the two uploaded spreadsheets (entity-tracker.xlsx and
 * board-meetings-calendar.xlsx). To refresh the data after the sheets change:
 *
 *     python3 prisma/data/parse_xlsx.py \
 *         prisma/data/entity-tracker.xlsx \
 *         prisma/data/board-meetings-calendar.xlsx
 *     npx prisma migrate reset          # wipes DB and re-runs this seed
 *
 * What gets seeded:
 *   - 7 application users (unchanged from previous seed)
 *   - 35 entities from Master Sheet (28 active + 7 dissolved), with parent links
 *   - Directors parsed from the D&Os column
 *   - Licenses parsed from the Licenses column (dates left null — unknown)
 *   - Board meetings parsed from the Subsidiaries Calendar sheet
 *
 * Intentionally NOT seeded (no data in spreadsheets):
 *   - ComplianceObligation
 *   - RegulatoryCapital
 *   - BankAccount
 *   - Alert
 *   - MeetingAttendee (attendee names are free-text and don't map 1:1 to directors)
 *   - MeetingDocument, MeetingResolution
 */
import { prisma } from '../lib/prisma';
import { readFileSync } from 'fs';
import { join } from 'path';

// ─────────────────────────────────────────────────────────────────────────────
// Helpers
// ─────────────────────────────────────────────────────────────────────────────

function toDate(s: string | Date | null | undefined): Date | undefined {
  if (!s) return undefined;
  const d = s instanceof Date ? s : new Date(s);
  return isNaN(d.getTime()) ? undefined : d;
}

// Strip keys whose value is `undefined` so Prisma doesn't interpret them as
// "missing required argument". `null` is kept — it's a valid NULL value for
// nullable columns.
// Strips keys whose value is `undefined` AND converts `null` -> undefined for
// non-nullable columns. Prisma treats explicit `undefined` as "field not set"
// (uses DB default / leaves nullable as NULL), which is what we want for
// optional fields whose types in the stale generated client may still be
// strict. Re-run `prisma generate` after any schema change to tighten this.
// eslint-disable-next-line @typescript-eslint/no-explicit-any
function clean<T extends Record<string, any>>(obj: T): T {
  return Object.fromEntries(
    Object.entries(obj)
      .filter(([, v]) => v !== undefined)
      .map(([k, v]) => [k, v === null ? undefined : v])
  ) as T;
}

function slugEmail(name: string): string {
  return (
    name
      .toLowerCase()
      .normalize('NFD')
      .replace(/[\u0300-\u036f]/g, '')
      .replace(/[^a-z0-9\s]/g, '')
      .trim()
      .replace(/\s+/g, '.') + '@governanceos.app'
  );
}

// ─────────────────────────────────────────────────────────────────────────────
// Data file
// ─────────────────────────────────────────────────────────────────────────────

interface DirectorRow {
  name: string;
  role: string;
}
interface LicenseRow {
  licenseType: string;
  licenseNumber: string;
  regulator: string;
}
interface EntityRow {
  id: string;
  name: string;
  country: string;
  legalStructure: string;
  registrationNumber: string;
  registeredAddress: string;
  incorporationDate: string | null;
  financialYearEnd: string;
  governingLaw: string;
  auditor: string | null;
  regulator: string | null;
  isLegacyEntity: boolean;
  status: 'active' | 'dormant' | 'dissolved' | 'in_formation';
  notes: string | null;
  parentEntityId: string | null;
  purpose?: string | null;
  minCapital?: string | null;
  corporateSecretary?: string | null;
  corporateSecretaryContact?: string | null;
  _directors: DirectorRow[];
  _licenses: LicenseRow[];
  _governance?: Record<string, string | null>;
}
interface MeetingRow {
  id: string;
  entityId: string;
  meetingType: string;
  meetingDate: string;
  meetingTime: string;
  timezone: string;
  locationType: 'physical' | 'virtual' | 'hybrid';
  location: string | null;
  virtualLink: string | null;
  agenda: string;
  chair: string;
  quorumRequired: number;
  status: 'draft' | 'scheduled' | 'completed' | 'cancelled';
  minutes: string | null;
  notes: string | null;
  recurrence: string | null;
  heldAt: string | null;
  confirmedBy: string | null;
  directorsPresent: number | null;
  minutesUrl: string | null;
  createdBy: string;
  _attendeesRaw?: string | null;
  _owner?: string | null;
  _circulationDeadline?: string | null;
  _materialsDeadline?: string | null;
  _minutesDeadline?: string | null;
}
interface DataFile {
  generatedAt: string;
  entities: EntityRow[];
  meetings: MeetingRow[];
}

const DATA_PATH = join(__dirname, 'data', 'seed-data.json');
const data: DataFile = JSON.parse(readFileSync(DATA_PATH, 'utf-8'));

// ─────────────────────────────────────────────────────────────────────────────
// MAIN
// ─────────────────────────────────────────────────────────────────────────────

async function main() {
  console.log('Starting seed...');
  console.log(`Data file generated: ${data.generatedAt}`);
  console.log(`Source: prisma/data/seed-data.json`);

  try {
    // ──────────────────────────────────────────────────────────────────────
    // USERS
    // ──────────────────────────────────────────────────────────────────────
    console.log('Seeding users...');
    // Only wipe the known seed user — never delete other orgs' users
    await prisma.user.deleteMany({ where: { id: 'usr-super-001' } });
    const users = [
      { id: 'usr-super-001', name: 'Ibrahim Oladele', email: 'ibrahim@monsterlabs.org', role: 'super_admin' as const, department: 'Executive', title: 'CEO', password: '$2b$12$L2eaActHHXheRsn22PXLROHXOyD9xKyEwdoXLE8EjHOqLv7xpDWv2' },
    ];
    for (const u of users) {
      await prisma.user.upsert({
        where: { email: u.email },
        update: clean({ ...u, isActive: true }),
        create: clean({ ...u, isActive: true }),
      });
    }
    console.log(`✓ Seeded ${users.length} users`);

    // ──────────────────────────────────────────────────────────────────────
    // ORGANISATION  (default tenant)
    // ──────────────────────────────────────────────────────────────────────
    console.log('Seeding default organisation...');
    const defaultOrg = await prisma.organisation.upsert({
      where: { slug: 'monster-labs' },
      update: { name: 'Monster Labs', plan: 'enterprise', isActive: true },
      create: { id: 'org-default-001', name: 'Monster Labs', slug: 'monster-labs', plan: 'enterprise', isActive: true },
    });
    // Add Ibrahim as super_admin member
    await prisma.organisationMember.upsert({
      where: { organisationId_userId: { organisationId: defaultOrg.id, userId: 'usr-super-001' } },
      update: { role: 'super_admin' },
      create: { organisationId: defaultOrg.id, userId: 'usr-super-001', role: 'super_admin' },
    });
    console.log(`✓ Organisation "${defaultOrg.name}" ready (id: ${defaultOrg.id})`);

    // ──────────────────────────────────────────────────────────────────────
    // ENTITIES  (two-pass to satisfy self-referential parentEntityId FK)
    // ──────────────────────────────────────────────────────────────────────
    console.log('Seeding entities...');
    for (const e of data.entities) {
      const notesParts: string[] = [];
      if (e.notes) notesParts.push(e.notes);
      if (e.purpose) notesParts.push(`Purpose: ${e.purpose}`);
      if (e.minCapital) notesParts.push(`Min. capital: ${e.minCapital}`);
      if (e.corporateSecretary) notesParts.push(`Corp sec: ${e.corporateSecretary}`);
      if (e.corporateSecretaryContact) notesParts.push(`Contact: ${e.corporateSecretaryContact}`);

      const data1 = clean({
        id: e.id,
        name: e.name,
        country: e.country,
        legalStructure: e.legalStructure,
        registrationNumber: e.registrationNumber || 'N/A',
        registeredAddress: e.registeredAddress || e.country,
        incorporationDate: toDate(e.incorporationDate) ?? new Date('2015-01-01'),
        financialYearEnd: e.financialYearEnd || '31 December',
        governingLaw: e.governingLaw || e.country,
        auditor: e.auditor,
        regulator: e.regulator,
        isLegacyEntity: e.isLegacyEntity,
        status: e.status,
        notes: notesParts.length ? notesParts.join('\n\n') : null,
        parentEntityId: null, // pass 2 sets this
        organisationId: defaultOrg.id,
      });
      await prisma.entity.upsert({ where: { id: e.id }, update: data1, create: data1 });
    }
    // Pass 2: parent linkage
    for (const e of data.entities) {
      if (e.parentEntityId) {
        await prisma.entity.update({
          where: { id: e.id },
          data: { parentEntityId: e.parentEntityId },
        });
      }
    }
    console.log(`✓ Seeded ${data.entities.length} entities (${data.entities.filter(e => e.status === 'active').length} active, ${data.entities.filter(e => e.status === 'dissolved').length} dissolved)`);

    // ──────────────────────────────────────────────────────────────────────
    // DIRECTORS
    // ──────────────────────────────────────────────────────────────────────
    console.log('Seeding directors...');
    // Only wipe directors belonging to the seed org — never delete other orgs' directors
    await prisma.director.deleteMany({ where: { entity: { organisationId: defaultOrg.id } } });
    let dirCount = 0;
    for (const e of data.entities) {
      let idx = 0;
      for (const d of e._directors) {
        idx += 1;
        const id = `dir-${e.id.replace(/^ent-/, '')}-${idx.toString().padStart(2, '0')}`;
        await prisma.director.create({
          // eslint-disable-next-line @typescript-eslint/no-explicit-any
          data: clean({
            id,
            entityId: e.id,
            name: d.name,
            email: slugEmail(d.name),
            role: d.role || 'Director',
            // appointmentDate is required — use entity incorporation date as proxy,
            // falling back to a sensible default when unknown
            appointmentDate: toDate(e.incorporationDate) ?? new Date('2020-01-01'),
            isActive: e.status === 'active',
          }) as any,
        });
        dirCount += 1;
      }
    }
    console.log(`✓ Seeded ${dirCount} directors`);

    // ──────────────────────────────────────────────────────────────────────
    // LICENSES
    // ──────────────────────────────────────────────────────────────────────
    console.log('Seeding licenses...');
    // Only wipe licenses belonging to the seed org
    await prisma.license.deleteMany({ where: { entity: { organisationId: defaultOrg.id } } });
    let licCount = 0;
    for (const e of data.entities) {
      let idx = 0;
      for (const l of e._licenses) {
        idx += 1;
        const id = `lic-${e.id.replace(/^ent-/, '')}-${idx.toString().padStart(2, '0')}`;
        await prisma.license.create({
          // eslint-disable-next-line @typescript-eslint/no-explicit-any
          data: clean({
            id,
            entityId: e.id,
            licenseType: l.licenseType,
            regulator: l.regulator || e.regulator || 'N/A',
            licenseNumber: l.licenseNumber || 'N/A',
            // issueDate / expiryDate are required — use incorporation date as proxy
            // for issue; default expiry to end of 2030 when unknown
            issueDate: toDate(e.incorporationDate) ?? new Date('2020-01-01'),
            expiryDate: new Date('2030-12-31'),
            renewalRequired: true,
            renewalLeadDays: 90,
            status: 'active' as const,
          }) as any,
        });
        licCount += 1;
      }
    }
    console.log(`✓ Seeded ${licCount} licenses`);

    // ──────────────────────────────────────────────────────────────────────
    // BOARD MEETINGS
    // ──────────────────────────────────────────────────────────────────────
    console.log('Seeding board meetings...');
    // Only wipe meetings belonging to the seed org
    await prisma.boardMeeting.deleteMany({ where: { entity: { organisationId: defaultOrg.id } } });
    for (const m of data.meetings) {
      // Enrich notes with calendar metadata
      const notesParts: string[] = [];
      if (m.notes) notesParts.push(`Status: ${m.notes}`);
      if (m._owner) notesParts.push(`Owner: ${m._owner}`);
      if (m._circulationDeadline) notesParts.push(`Agenda circulation deadline: ${m._circulationDeadline}`);
      if (m._materialsDeadline) notesParts.push(`Materials circulation deadline: ${m._materialsDeadline}`);
      if (m._minutesDeadline) notesParts.push(`Minutes circulation deadline: ${m._minutesDeadline}`);
      if (m._attendeesRaw) notesParts.push(`Attendees (raw):\n${m._attendeesRaw}`);

      await prisma.boardMeeting.create({
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        data: clean({
          id: m.id,
          entityId: m.entityId,
          meetingType: m.meetingType,
          // Use toDate() so invalid/missing date strings (e.g. "TBD") don't
          // produce new Date("Invalid Date") — fall back to end of current year
          meetingDate: toDate(m.meetingDate) ?? new Date('2025-12-31'),
          meetingTime: m.meetingTime || 'TBD',
          timezone: m.timezone || 'UTC',
          locationType: m.locationType,
          location: m.location,
          virtualLink: m.virtualLink,
          agenda: m.agenda || 'Standard board agenda',
          chair: m.chair || 'TBD',
          quorumRequired: m.quorumRequired ?? 2,
          status: m.status,
          minutes: m.minutes,
          notes: notesParts.length ? notesParts.join('\n') : null,
          recurrence: m.recurrence,
          heldAt: toDate(m.heldAt),
          confirmedBy: m.confirmedBy,
          directorsPresent: m.directorsPresent,
          minutesUrl: m.minutesUrl,
          createdBy: m.createdBy || 'usr-legal-001',
        }) as any,
      });
    }
    console.log(`✓ Seeded ${data.meetings.length} board meetings`);

    console.log('\nSeed complete ✓');
    console.log('Compliance, Capital, Alerts, BankAccounts intentionally empty (no source data).');
  } catch (err) {
    console.error('Error seeding database:', err);
    throw err;
  }
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
